export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const FETCH_BRAND_PHONES = 'FETCH_BRAND_PHONES';
export const REMOVE_FROM_COMPARE = 'REMOVE_FROM_COMPARE';
export const SAVE_BRANDS_TO_STORE = 'SAVE_BRANDS_TO_STORE';
export const SAVE_PHONES_TO_STORE = 'SAVE_PHONES_TO_STORE';

